lib/curl_poll.h: fix header guard collision with musl libc
The musl libc uses the _POLL_H macro as a double include guard for the poll.h
header. This breaks compilation of files the include curl_poll.h:

In file included from driver.h:32:0,
                 from driver.c:12:
lirc/curl_poll.h:38:29: error: array type has incomplete element type ‘struct pollfd’
 int curl_poll(struct pollfd ufds[], unsigned int nfds, int timeout_ms);
                             ^~~~

Rename the curl_poll.h header guard macro to avoid collision. Don't use a name
that starts with an underscore and a capital letter since these names are
reserved according to the ANSI C standard.

https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

Signed-off-by: Baruch Siach <baruch@tkos.co.il>